#!/usr/bin/env python3
"""Rewrite the icon mask table in app.css from the names in icons.txt.

Each Lucide SVG is fetched, stripped of its presentation attributes and inlined
as a data: URI behind an --icon custom property. Colors and stroke weight are
declared once in the .i rule instead, so making every icon heavier is one edit
rather than eighteen.

Needs the network. It is not a build step: the output is committed, and this
runs only when icons.txt changes.

Run: python3 docs/design/icons.py
"""

import os
import re
import sys
import urllib.parse
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
SOURCE = "https://unpkg.com/lucide-static@latest/icons/%s.svg"

# Generated content cannot carry a class, so the icons a pseudo-element draws
# are bound to :root as well.
FOR_PSEUDO = ("chevron-right", "check")

OPEN = "/* >>> icons: generated by icons.py, do not edit by hand <<< */"
CLOSE = "/* <<< end icons */"


def fetch(name):
    with urllib.request.urlopen(SOURCE % name, timeout=30) as response:
        return response.read().decode()


def to_uri(svg):
    """One SVG as a data: URI small enough to sit in a stylesheet."""
    svg = re.sub(r"<!--.*?-->", "", svg, flags=re.S).strip()
    svg = re.sub(r"\s+", " ", svg)
    for attr in ("width", "height", "stroke", "fill", "stroke-width",
                 "stroke-linecap", "stroke-linejoin", "class"):
        svg = re.sub(r'\s%s="[^"]*"' % attr, "", svg, count=1)
    # The source already declares xmlns. A second one is invalid XML, and a
    # strict parser drops the whole image rather than the stray attribute.
    svg = re.sub(r'\s*xmlns="[^"]*"', "", svg, count=1)
    svg = svg.replace("<svg ", "<svg xmlns='http://www.w3.org/2000/svg' "
                               "fill='none' stroke='black' stroke-width='2' "
                               "stroke-linecap='round' stroke-linejoin='round' ", 1)
    svg = svg.replace("> <", "><").replace(" />", "/>").replace('" >', '">')
    svg = svg.replace('"', "'")
    return urllib.parse.quote(svg, safe="/:=' ()<>,.-#")


def main():
    names = open(os.path.join(HERE, "icons.txt")).read().strip().split(",")
    names = [n.strip() for n in names if n.strip()]
    if len(names) != len(set(names)):
        print("icons.txt lists a name twice", file=sys.stderr)
        return 1

    uris = {}
    for name in names:
        try:
            uris[name] = to_uri(fetch(name))
        except Exception as err:
            print("%s: %s (is that a name on lucide.dev?)" % (name, err),
                  file=sys.stderr)
            return 1

    out = [OPEN, ""]
    for name in FOR_PSEUDO:
        if name not in uris:
            print("%s is drawn by generated content and must stay in icons.txt"
                  % name, file=sys.stderr)
            return 1
    out.append(":root {")
    for name in FOR_PSEUDO:
        out.append('  --icon-%s: url("data:image/svg+xml,%s");' % (name, uris[name]))
    out.append("}")
    out.append("")
    for name in names:
        out.append(".i-%s {" % name)
        out.append('  --icon: url("data:image/svg+xml,%s");' % uris[name])
        out.append("}")
        out.append("")
    out.append(CLOSE)
    table = "\n".join(out)

    path = os.path.join(HERE, "app.css")
    css = open(path).read()
    if OPEN not in css or CLOSE not in css:
        print("app.css has no icon block to replace; expected %s" % OPEN,
              file=sys.stderr)
        return 1
    start = css.index(OPEN)
    end = css.index(CLOSE) + len(CLOSE)
    open(path, "w").write(css[:start] + table + css[end:])
    print("wrote %d masks into app.css (%d bytes)" % (len(names), len(table)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
