// Command icons rewrites the icon mask table in app.css from the names in
// icons.txt.
//
// Each Lucide SVG is fetched, stripped of its presentation attributes and
// inlined as a data: URI behind an --icon custom property. Color and stroke
// weight are declared once in the .i rule instead, so making every icon heavier
// is one edit rather than eighteen.
//
// It needs the network and is not a build step. The output is committed, and
// this runs only when icons.txt changes.
package main

import (
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"github.com/cockroachdb/errors"
)

// source is where one Lucide icon is fetched from, by name.
const source = "https://unpkg.com/lucide-static@latest/icons/%s.svg"

// designDir holds icons.txt and app.css, relative to the repository root.
const designDir = "docs/design"

// openMarker and closeMarker bound the block this command owns. Everything
// outside them is hand-written and is copied through untouched.
const (
	openMarker  = "/* >>> icons: generated by tool/icons, do not edit by hand <<< */"
	closeMarker = "/* <<< end icons */"
)

// forPseudo are the icons a pseudo-element draws.
//
// Generated content cannot carry a class, so these are bound to :root as well
// and dropping one from icons.txt would leave a caret that draws nothing.
var forPseudo = []string{"chevron-right", "check"}

// stripAttrs are the presentation attributes removed from each SVG, because the
// .i rule declares them once for every icon.
var stripAttrs = []string{
	"class",
	"fill",
	"height",
	"stroke",
	"stroke-linecap",
	"stroke-linejoin",
	"stroke-width",
	"width",
}

// svgOpen is what each SVG's root tag becomes, carrying the presentation the
// stripped attributes used to carry.
const svgOpen = "<svg xmlns='http://www.w3.org/2000/svg' fill='none' stroke='black' stroke-width='2' stroke-linecap='round' stroke-linejoin='round' "

var (
	// commentPattern matches an XML comment, which no icon needs.
	commentPattern = regexp.MustCompile(`(?s)<!--.*?-->`)
	// spacePattern matches a run of whitespace, which collapses to one space.
	spacePattern = regexp.MustCompile(`\s+`)
	// xmlnsPattern matches the namespace the source already declares. A second
	// one is invalid XML, and a strict parser drops the whole image rather than
	// the stray attribute.
	xmlnsPattern = regexp.MustCompile(`\s*xmlns="[^"]*"`)
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "icons: %v\n", err)
		os.Exit(1)
	}
}

// run regenerates the table, or reports why it could not.
func run() error {
	root, err := repoRoot()
	if err != nil {
		return err
	}
	dir := filepath.Join(root, designDir)
	names, err := readNames(filepath.Join(dir, "icons.txt"))
	if err != nil {
		return err
	}
	uris := map[string]string{}
	for _, name := range names {
		svg, err := fetch(name)
		if err != nil {
			return errors.Wrapf(err, "%s (is that a name on lucide.dev?)", name)
		}
		uris[name] = toURI(svg)
	}
	for _, name := range forPseudo {
		if _, ok := uris[name]; !ok {
			return errors.Newf("%s is drawn by generated content and must stay in icons.txt", name)
		}
	}
	table := buildTable(names, uris)
	path := filepath.Join(dir, "app.css")
	css, err := os.ReadFile(path)
	if err != nil {
		return errors.Wrapf(err, "read %s", path)
	}
	next, err := splice(string(css), table)
	if err != nil {
		return err
	}
	if err := os.WriteFile(path, []byte(next), 0o644); err != nil {
		return errors.Wrapf(err, "write %s", path)
	}
	fmt.Printf("wrote %d masks into app.css (%d bytes)\n", len(names), len(table))
	return nil
}

// repoRoot walks up from the working directory for the module root.
func repoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", errors.WithStack(err)
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", errors.New("no go.mod above the working directory")
		}
		dir = parent
	}
}

// readNames reads icons.txt, which is one comma-separated list.
func readNames(path string) ([]string, error) {
	body, err := os.ReadFile(path)
	if err != nil {
		return nil, errors.Wrapf(err, "read %s", path)
	}
	var names []string
	seen := map[string]struct{}{}
	for _, name := range strings.Split(strings.TrimSpace(string(body)), ",") {
		name = strings.TrimSpace(name)
		if name == "" {
			continue
		}
		if _, ok := seen[name]; ok {
			return nil, errors.Newf("icons.txt lists %s twice", name)
		}
		seen[name] = struct{}{}
		names = append(names, name)
	}
	return names, nil
}

// fetch reads one icon from Lucide.
func fetch(name string) (string, error) {
	client := &http.Client{Timeout: 30 * time.Second}
	resp, err := client.Get(fmt.Sprintf(source, name))
	if err != nil {
		return "", errors.WithStack(err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return "", errors.Newf("%s", resp.Status)
	}
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", errors.WithStack(err)
	}
	return string(body), nil
}

// toURI is one SVG as a data: URI small enough to sit in a stylesheet.
func toURI(svg string) string {
	svg = strings.TrimSpace(commentPattern.ReplaceAllString(svg, ""))
	svg = spacePattern.ReplaceAllString(svg, " ")
	for _, attr := range stripAttrs {
		pattern := regexp.MustCompile(`\s` + regexp.QuoteMeta(attr) + `="[^"]*"`)
		svg = replaceFirst(pattern, svg)
	}
	svg = replaceFirst(xmlnsPattern, svg)
	svg = strings.Replace(svg, "<svg ", svgOpen, 1)
	svg = strings.ReplaceAll(svg, "> <", "><")
	svg = strings.ReplaceAll(svg, " />", "/>")
	svg = strings.ReplaceAll(svg, `" >`, `">`)
	svg = strings.ReplaceAll(svg, `"`, "'")
	return percentEncode(svg)
}

// replaceFirst removes the first match, which is what a count of one means in
// the Python this was ported from.
func replaceFirst(pattern *regexp.Regexp, s string) string {
	loc := pattern.FindStringIndex(s)
	if loc == nil {
		return s
	}
	return s[:loc[0]] + s[loc[1]:]
}

// uriSafe are the bytes left alone by percentEncode.
//
// This is Python's urllib.parse.quote with safe="/:=' ()<>,.-#", which always
// keeps the unreserved set on top of whatever it is given. The output is
// committed, so any difference here shows up as a diff in app.css.
const uriSafe = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_.-~/:=' ()<>,#"

// percentEncode escapes every byte outside uriSafe, in uppercase hex.
func percentEncode(s string) string {
	var sb strings.Builder
	for i := 0; i < len(s); i++ {
		c := s[i]
		if strings.IndexByte(uriSafe, c) >= 0 {
			sb.WriteByte(c)
			continue
		}
		fmt.Fprintf(&sb, "%%%02X", c)
	}
	return sb.String()
}

// buildTable renders the block, with the pseudo-element bindings first.
func buildTable(names []string, uris map[string]string) string {
	var out []string
	out = append(out, openMarker, "")
	out = append(out, ":root {")
	for _, name := range forPseudo {
		out = append(out, fmt.Sprintf(`  --icon-%s: url("data:image/svg+xml,%s");`, name, uris[name]))
	}
	out = append(out, "}", "")
	for _, name := range names {
		out = append(out, fmt.Sprintf(".i-%s {", name))
		out = append(out, fmt.Sprintf(`  --icon: url("data:image/svg+xml,%s");`, uris[name]))
		out = append(out, "}", "")
	}
	out = append(out, closeMarker)
	return strings.Join(out, "\n")
}

// splice replaces the generated block, leaving everything outside it untouched.
//
// The opening marker is matched loosely, because the block that is there was
// written by the Python this replaced and names that script instead.
func splice(css string, table string) (string, error) {
	openPattern := regexp.MustCompile(`/\* >>> icons: generated by [^*]* <<< \*/`)
	loc := openPattern.FindStringIndex(css)
	end := strings.Index(css, closeMarker)
	if loc == nil || end < 0 {
		return "", errors.Newf("app.css has no icon block to replace; expected %s", openMarker)
	}
	return css[:loc[0]] + table + css[end+len(closeMarker):], nil
}
